#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

echo "Restoring case to default . . ."

rm -rf postProcessing
rm -rf processor*
rm -rf 0
rm -rf 0.0* 0.1 {1..1000}*
rm -rf *e-*
rm -rf log*

echo "Done."

#------------------------------------------------------------------------------
